import { describe, expect, it } from "vitest"

import {
  buildReleaseManifest,
  buildCleanMachineInstallChecklist,
  buildReleasePipelinePlan,
} from "../packages/core/src/release/package.ts"
import {
  ACTIVE_TAB_INFO_RELEASE_GATE_EVIDENCE_REQUIREMENTS,
} from "../packages/core/src/release/yeonjang-browser-active-tab-info-release-gate-evidence-collector.ts"

describe("Task 218 Yeonjang browser.active_tab_info release manifest entry", () => {
  it("adds active tab info release gate to packaging pipeline without enabling live paths", () => {
    const pipeline = buildReleasePipelinePlan({ targetPlatforms: ["macos", "windows", "linux"] })

    expect(pipeline.order).toContain("yeonjang-browser-active-tab-info-release-gate")
    expect(pipeline.order).toContain("release-approval-candidate-preparation")
    const approvalStep = pipeline.steps.find(
      (item) => item.id === "release-approval-candidate-preparation",
    )
    expect(approvalStep).toMatchObject({
      id: "release-approval-candidate-preparation",
      title: "Release approval candidate preparation",
      command: [
        "pnpm",
        "run",
        "release:prepare-approval-candidate",
        "--",
        "--candidate",
        "<performance-or-rollout-candidate.json>",
        "--release-dry-run",
        "<release-dry-run.json>",
        "--output",
        "<prepared-approval-candidate.json>",
      ],
      required: true,
      smoke: false,
    })
    expect(approvalStep?.description).toContain("releaseApprovalEvidence")
    expect(approvalStep?.description).toContain("release:authorize")
    expect(approvalStep?.description).not.toMatch(
      /threshold\/baseline raw detail exposed|raw audit JSON exposed|local absolute path exposed/iu,
    )
    const step = pipeline.steps.find((item) => item.id === "yeonjang-browser-active-tab-info-release-gate")
    expect(step).toMatchObject({
      id: "yeonjang-browser-active-tab-info-release-gate",
      title: "Yeonjang browser active tab info release gate",
      command: [
        "pnpm",
        "exec",
        "vitest",
        "run",
        "tests/task279-active-tab-info-terminal-report-projection-misuse-guard.test.ts",
        "tests/task281-active-tab-info-terminal-delivery-receipt-misuse-guard.test.ts",
        "tests/task280-active-tab-info-terminal-delivery-receipt.test.ts",
        "tests/task283-active-tab-info-operator-closeout-note-misuse-guard.test.ts",
        "tests/task282-active-tab-info-operator-closeout-note.test.ts",
        "tests/task285-active-tab-info-final-closeout-ledger-misuse-guard.test.ts",
        "tests/task284-active-tab-info-final-closeout-ledger.test.ts",
        "tests/task458-active-tab-info-release-evidence-chain-cleanup-deletion-review-receipt-misuse-guard.test.ts",
        "tests/task457-active-tab-info-release-evidence-chain-cleanup-deletion-review-receipt.test.ts",
        "tests/task460-active-tab-info-release-evidence-chain-cleanup-deletion-execution-admission-misuse-guard.test.ts",
        "tests/task459-active-tab-info-release-evidence-chain-cleanup-deletion-execution-admission.test.ts",
        "tests/task464-active-tab-info-release-evidence-chain-cleanup-deletion-dry-run-review-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task463-active-tab-info-release-evidence-chain-cleanup-deletion-dry-run-review-acknowledgement-receipt.test.ts",
        "tests/task462-active-tab-info-release-evidence-chain-cleanup-deletion-dry-run-receipt-misuse-guard.test.ts",
        "tests/task461-active-tab-info-release-evidence-chain-cleanup-deletion-dry-run-receipt.test.ts",
        "tests/task456-active-tab-info-release-evidence-chain-cleanup-deletion-candidate-plan-misuse-guard.test.ts",
        "tests/task455-active-tab-info-release-evidence-chain-cleanup-deletion-candidate-plan.test.ts",
        "tests/task454-active-tab-info-release-evidence-chain-cleanup-branch-execution-admission-misuse-guard.test.ts",
        "tests/task453-active-tab-info-release-evidence-chain-cleanup-branch-execution-admission.test.ts",
        "tests/task452-active-tab-info-release-evidence-chain-cleanup-branch-preparation-plan-misuse-guard.test.ts",
        "tests/task451-active-tab-info-release-evidence-chain-cleanup-branch-preparation-plan.test.ts",
        "tests/task450-active-tab-info-release-evidence-chain-cleanup-pr-review-receipt-misuse-guard.test.ts",
        "tests/task449-active-tab-info-release-evidence-chain-cleanup-pr-review-receipt.test.ts",
        "tests/task448-active-tab-info-release-evidence-chain-cleanup-pr-checklist-misuse-guard.test.ts",
        "tests/task447-active-tab-info-release-evidence-chain-cleanup-pr-checklist.test.ts",
        "tests/task446-active-tab-info-release-evidence-chain-cleanup-readiness-index-misuse-guard.test.ts",
        "tests/task445-active-tab-info-release-evidence-chain-cleanup-readiness-index.test.ts",
        "tests/task444-active-tab-info-release-evidence-chain-cleanup-task-plan-summary-misuse-guard.test.ts",
        "tests/task443-active-tab-info-release-evidence-chain-cleanup-task-plan-summary.test.ts",
        "tests/task442-active-tab-info-release-evidence-chain-tidy-first-cleanup-task-plan.test.ts",
        "tests/task441-active-tab-info-release-evidence-chain-cleanup-approval-gate.test.ts",
        "tests/task440-active-tab-info-release-evidence-chain-cleanup-proposal.test.ts",
        "tests/task439-active-tab-info-release-evidence-chain-architecture-review.test.ts",
        "tests/task438-active-tab-info-release-evidence-chain-termination.test.ts",
        "tests/task437-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-closure-ledger-receipt-misuse-guard.test.ts",
        "tests/task436-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-closure-ledger-receipt.test.ts",
        "tests/task435-active-tab-info-final-retained-acknowledgement-completion-closeout-acknowledgement-closure-ledger-misuse-guard.test.ts",
        "tests/task434-active-tab-info-final-retained-acknowledgement-completion-closeout-acknowledgement-closure-ledger.test.ts",
        "tests/task433-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-ledger-receipt-misuse-guard.test.ts",
        "tests/task432-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-ledger-receipt.test.ts",
        "tests/task431-active-tab-info-final-retained-acknowledgement-completion-closeout-acknowledgement-ledger-misuse-guard.test.ts",
        "tests/task430-active-tab-info-final-retained-acknowledgement-completion-closeout-acknowledgement-ledger.test.ts",
        "tests/task429-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task428-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-receipt.test.ts",
        "tests/task427-active-tab-info-final-retained-acknowledgement-completion-closeout-ledger-misuse-guard.test.ts",
        "tests/task426-active-tab-info-final-retained-acknowledgement-completion-closeout-ledger.test.ts",
        "tests/task425-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-receipt-misuse-guard.test.ts",
        "tests/task424-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-receipt.test.ts",
        "tests/task423-active-tab-info-final-retained-acknowledgement-completion-ledger-misuse-guard.test.ts",
        "tests/task422-active-tab-info-final-retained-acknowledgement-completion-ledger.test.ts",
        "tests/task421-active-tab-info-operator-final-retained-acknowledgement-completion-receipt-misuse-guard.test.ts",
        "tests/task420-active-tab-info-operator-final-retained-acknowledgement-completion-receipt.test.ts",
        "tests/task419-active-tab-info-final-acknowledgement-ledger-misuse-guard.test.ts",
        "tests/task418-active-tab-info-final-acknowledgement-ledger.test.ts",
        "tests/task417-active-tab-info-operator-final-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task416-active-tab-info-operator-final-acknowledgement-receipt.test.ts",
        "tests/task415-active-tab-info-final-completion-ledger-misuse-guard.test.ts",
        "tests/task414-active-tab-info-final-completion-ledger.test.ts",
        "tests/task413-active-tab-info-operator-final-completion-receipt-misuse-guard.test.ts",
        "tests/task412-active-tab-info-operator-final-completion-receipt.test.ts",
        "tests/task411-active-tab-info-final-retained-completion-ledger-misuse-guard.test.ts",
        "tests/task410-active-tab-info-final-retained-completion-ledger.test.ts",
        "tests/task409-active-tab-info-operator-final-retained-completion-receipt-misuse-guard.test.ts",
        "tests/task408-active-tab-info-operator-final-retained-completion-receipt.test.ts",
        "tests/task407-active-tab-info-final-retained-sealed-completion-ledger-misuse-guard.test.ts",
        "tests/task406-active-tab-info-final-retained-sealed-completion-ledger.test.ts",
        "tests/task405-active-tab-info-operator-final-retained-sealed-completion-receipt-misuse-guard.test.ts",
        "tests/task404-active-tab-info-operator-final-retained-sealed-completion-receipt.test.ts",
        "tests/task403-active-tab-info-final-retained-sealed-closeout-completion-ledger-misuse-guard.test.ts",
        "tests/task402-active-tab-info-final-retained-sealed-closeout-completion-ledger.test.ts",
        "tests/task401-active-tab-info-operator-final-retained-sealed-closeout-completion-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task400-active-tab-info-operator-final-retained-sealed-closeout-completion-acknowledgement-receipt.test.ts",
        "tests/task399-active-tab-info-final-retained-sealed-closeout-acknowledgement-ledger-misuse-guard.test.ts",
        "tests/task398-active-tab-info-final-retained-sealed-closeout-acknowledgement-ledger.test.ts",
        "tests/task397-active-tab-info-operator-final-retained-sealed-closeout-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task396-active-tab-info-operator-final-retained-sealed-closeout-acknowledgement-receipt.test.ts",
        "tests/task395-active-tab-info-final-retained-sealed-closeout-ledger-misuse-guard.test.ts",
        "tests/task394-active-tab-info-final-retained-sealed-closeout-ledger.test.ts",
        "tests/task393-active-tab-info-operator-final-retained-closeout-sealed-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task392-active-tab-info-operator-final-retained-closeout-sealed-acknowledgement-receipt.test.ts",
        "tests/task391-active-tab-info-final-retained-closeout-sealed-ledger-misuse-guard.test.ts",
        "tests/task390-active-tab-info-final-retained-closeout-sealed-ledger.test.ts",
        "tests/task389-active-tab-info-operator-final-retained-completion-closeout-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task388-active-tab-info-operator-final-retained-completion-closeout-acknowledgement-receipt.test.ts",
        "tests/task387-active-tab-info-final-retained-completion-closeout-ledger-misuse-guard.test.ts",
        "tests/task386-active-tab-info-final-retained-completion-closeout-ledger.test.ts",
        "tests/task385-active-tab-info-operator-final-retained-closeout-completion-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task384-active-tab-info-operator-final-retained-closeout-completion-acknowledgement-receipt.test.ts",
        "tests/task383-active-tab-info-final-retained-closeout-completion-ledger-misuse-guard.test.ts",
        "tests/task382-active-tab-info-final-retained-closeout-completion-ledger.test.ts",
        "tests/task381-active-tab-info-operator-final-retained-closeout-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task380-active-tab-info-operator-final-retained-closeout-acknowledgement-receipt.test.ts",
        "tests/task379-active-tab-info-final-retained-closeout-acknowledgement-ledger-misuse-guard.test.ts",
        "tests/task378-active-tab-info-final-retained-closeout-acknowledgement-ledger.test.ts",
        "tests/task377-active-tab-info-operator-retained-closeout-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task376-active-tab-info-operator-retained-closeout-acknowledgement-receipt.test.ts",
        "tests/task375-active-tab-info-final-retained-seal-closeout-ledger-misuse-guard.test.ts",
        "tests/task374-active-tab-info-final-retained-seal-closeout-ledger.test.ts",
        "tests/task373-active-tab-info-operator-retained-seal-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task372-active-tab-info-operator-retained-seal-acknowledgement-receipt.test.ts",
        "tests/task371-active-tab-info-final-retained-ledger-acknowledgement-seal-misuse-guard.test.ts",
        "tests/task370-active-tab-info-final-retained-ledger-acknowledgement-seal.test.ts",
        "tests/task369-active-tab-info-operator-retained-ledger-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task368-active-tab-info-operator-retained-ledger-acknowledgement-receipt.test.ts",
        "tests/task367-active-tab-info-final-retained-completion-acknowledgement-ledger-misuse-guard.test.ts",
        "tests/task366-active-tab-info-final-retained-completion-acknowledgement-ledger.test.ts",
        "tests/task365-active-tab-info-operator-retained-completion-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task364-active-tab-info-operator-retained-completion-acknowledgement-receipt.test.ts",
        "tests/task363-active-tab-info-final-retained-completion-index-misuse-guard.test.ts",
        "tests/task362-active-tab-info-final-retained-completion-index.test.ts",
        "tests/task361-active-tab-info-operator-final-retained-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task360-active-tab-info-operator-final-retained-acknowledgement-receipt.test.ts",
        "tests/task359-active-tab-info-final-retained-acknowledgement-ledger-misuse-guard.test.ts",
        "tests/task358-active-tab-info-final-retained-acknowledgement-ledger.test.ts",
        "tests/task357-active-tab-info-operator-retained-transfer-index-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task356-active-tab-info-operator-retained-transfer-index-acknowledgement-receipt.test.ts",
        "tests/task355-active-tab-info-final-retained-transfer-index-misuse-guard.test.ts",
        "tests/task354-active-tab-info-final-retained-transfer-index.test.ts",
        "tests/task353-active-tab-info-operator-post-transfer-archive-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task352-active-tab-info-operator-post-transfer-archive-acknowledgement-receipt.test.ts",
        "tests/task351-active-tab-info-final-post-transfer-archive-pointer-misuse-guard.test.ts",
        "tests/task350-active-tab-info-final-post-transfer-archive-pointer.test.ts",
        "tests/task349-active-tab-info-operator-final-transfer-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task348-active-tab-info-operator-final-transfer-acknowledgement-receipt.test.ts",
        "tests/task347-active-tab-info-final-transfer-closeout-ledger-misuse-guard.test.ts",
        "tests/task346-active-tab-info-final-transfer-closeout-ledger.test.ts",
        "tests/task345-active-tab-info-operator-final-handoff-receipt-misuse-guard.test.ts",
        "tests/task344-active-tab-info-operator-final-handoff-receipt.test.ts",
        "tests/task343-active-tab-info-final-handoff-closure-marker-misuse-guard.test.ts",
        "tests/task342-active-tab-info-final-handoff-closure-marker.test.ts",
        "tests/task341-active-tab-info-operator-final-retention-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task340-active-tab-info-operator-final-retention-acknowledgement-receipt.test.ts",
        "tests/task339-active-tab-info-final-retention-closure-ledger-misuse-guard.test.ts",
        "tests/task338-active-tab-info-final-retention-closure-ledger.test.ts",
        "tests/task337-active-tab-info-operator-final-index-retention-receipt-misuse-guard.test.ts",
        "tests/task336-active-tab-info-operator-final-index-retention-receipt.test.ts",
        "tests/task335-active-tab-info-final-operator-closeout-index-misuse-guard.test.ts",
        "tests/task334-active-tab-info-final-operator-closeout-index.test.ts",
        "tests/task333-active-tab-info-operator-final-closeout-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task332-active-tab-info-operator-final-closeout-acknowledgement-receipt.test.ts",
        "tests/task331-active-tab-info-final-sealed-archive-closeout-ledger-misuse-guard.test.ts",
        "tests/task330-active-tab-info-final-sealed-archive-closeout-ledger.test.ts",
        "tests/task329-active-tab-info-operator-final-sealed-archive-receipt-misuse-guard.test.ts",
        "tests/task328-active-tab-info-operator-final-sealed-archive-receipt.test.ts",
        "tests/task327-active-tab-info-final-sealed-archive-handoff-completion-index-misuse-guard.test.ts",
        "tests/task326-active-tab-info-final-sealed-archive-handoff-completion-index.test.ts",
        "tests/task325-active-tab-info-operator-sealed-archive-handoff-receipt-misuse-guard.test.ts",
        "tests/task324-active-tab-info-operator-sealed-archive-handoff-receipt.test.ts",
        "tests/task323-active-tab-info-final-sealed-archive-handoff-marker-misuse-guard.test.ts",
        "tests/task322-active-tab-info-final-sealed-archive-handoff-marker.test.ts",
        "tests/task321-active-tab-info-operator-sealed-completion-archive-receipt-misuse-guard.test.ts",
        "tests/task320-active-tab-info-operator-sealed-completion-archive-receipt.test.ts",
        "tests/task319-active-tab-info-final-completion-archive-seal-misuse-guard.test.ts",
        "tests/task318-active-tab-info-final-completion-archive-seal.test.ts",
        "tests/task317-active-tab-info-operator-completion-archive-acknowledgement-misuse-guard.test.ts",
        "tests/task316-active-tab-info-operator-completion-archive-acknowledgement.test.ts",
        "tests/task315-active-tab-info-final-operator-archive-completion-marker-misuse-guard.test.ts",
        "tests/task314-active-tab-info-final-operator-archive-completion-marker.test.ts",
        "tests/task313-active-tab-info-operator-archival-completion-acknowledgement-receipt-misuse-guard.test.ts",
        "tests/task312-active-tab-info-operator-archival-completion-acknowledgement-receipt.test.ts",
        "tests/task311-active-tab-info-final-archival-completion-index-misuse-guard.test.ts",
        "tests/task310-active-tab-info-final-archival-completion-index.test.ts",
        "tests/task309-active-tab-info-operator-archived-release-acknowledgement-misuse-guard.test.ts",
        "tests/task308-active-tab-info-operator-archived-release-acknowledgement.test.ts",
        "tests/task307-active-tab-info-final-archived-release-closure-marker-misuse-guard.test.ts",
        "tests/task306-active-tab-info-final-archived-release-closure-marker.test.ts",
        "tests/task305-active-tab-info-operator-archive-index-retention-receipt-misuse-guard.test.ts",
        "tests/task304-active-tab-info-operator-archive-index-retention-receipt.test.ts",
        "tests/task303-active-tab-info-final-release-archive-index-pointer-misuse-guard.test.ts",
        "tests/task302-active-tab-info-final-release-archive-index-pointer.test.ts",
        "tests/task301-active-tab-info-operator-release-archive-completion-notice-misuse-guard.test.ts",
        "tests/task300-active-tab-info-operator-release-archive-completion-notice.test.ts",
        "tests/task299-active-tab-info-final-audit-release-closure-ledger-misuse-guard.test.ts",
        "tests/task298-active-tab-info-final-audit-release-closure-ledger.test.ts",
        "tests/task297-active-tab-info-final-audit-release-handoff-receipt-misuse-guard.test.ts",
        "tests/task296-active-tab-info-final-audit-release-handoff-receipt.test.ts",
        "tests/task295-active-tab-info-archival-release-evidence-index-misuse-guard.test.ts",
        "tests/task294-active-tab-info-archival-release-evidence-index.test.ts",
        "tests/task293-active-tab-info-final-archival-pointer-misuse-guard.test.ts",
        "tests/task292-active-tab-info-final-archival-pointer.test.ts",
        "tests/task291-active-tab-info-operator-readable-closeout-summary-misuse-guard.test.ts",
        "tests/task290-active-tab-info-operator-readable-closeout-summary.test.ts",
        "tests/task289-active-tab-info-operator-completion-notice-misuse-guard.test.ts",
        "tests/task288-active-tab-info-operator-completion-notice.test.ts",
        "tests/task287-active-tab-info-final-audit-handoff-bundle-misuse-guard.test.ts",
        "tests/task286-active-tab-info-final-audit-handoff-bundle.test.ts",
        "tests/task278-active-tab-info-terminal-report-projection.test.ts",
        "tests/task277-active-tab-info-completion-audit-summary-misuse-guard.test.ts",
        "tests/task276-active-tab-info-completion-audit-summary.test.ts",
        "tests/task275-active-tab-info-user-goal-closeout-receipt-misuse-guard.test.ts",
        "tests/task274-active-tab-info-user-goal-closeout-receipt.test.ts",
        "tests/task273-active-tab-info-final-response-delivery-gate-misuse-guard.test.ts",
        "tests/task272-active-tab-info-final-response-delivery-gate.test.ts",
        "tests/task271-active-tab-info-llm-post-check-decision-receipt-misuse-guard.test.ts",
        "tests/task270-active-tab-info-llm-post-check-decision-receipt.test.ts",
        "tests/task269-active-tab-info-dispatch-verification-admission-misuse-guard.test.ts",
        "tests/task268-active-tab-info-dispatch-verification-admission.test.ts",
        "tests/task267-active-tab-info-dispatch-execution-receipt-misuse-guard.test.ts",
        "tests/task266-active-tab-info-dispatch-execution-receipt.test.ts",
        "tests/task265-active-tab-info-dispatch-dry-run-receipt-misuse-guard.test.ts",
        "tests/task264-active-tab-info-dispatch-dry-run-receipt.test.ts",
        "tests/task263-active-tab-info-dispatch-execution-plan-misuse-guard.test.ts",
        "tests/task262-active-tab-info-dispatch-execution-plan.test.ts",
        "tests/task261-active-tab-info-live-execution-receipt-misuse-guard.test.ts",
        "tests/task260-active-tab-info-live-execution-receipt-contract.test.ts",
        "tests/task259-active-tab-info-live-execution-authorization-misuse-guard.test.ts",
        "tests/task258-active-tab-info-live-execution-authorization-contract.test.ts",
        "tests/task257-active-tab-info-runtime-mutation-dry-run-receipt-misuse-guard.test.ts",
        "tests/task256-active-tab-info-runtime-mutation-dry-run-receipt.test.ts",
        "tests/task255-active-tab-info-runtime-mutation-executor-plan-misuse-guard.test.ts",
        "tests/task254-active-tab-info-runtime-mutation-executor-plan.test.ts",
        "tests/task253-active-tab-info-runtime-mutation-preflight-misuse-guard.test.ts",
        "tests/task252-active-tab-info-runtime-mutation-preflight.test.ts",
        "tests/task251-active-tab-info-runtime-change-skeleton-misuse-guard.test.ts",
        "tests/task250-active-tab-info-runtime-change-skeleton.test.ts",
        "tests/task249-active-tab-info-authorization-executor-bridge-misuse-guard.test.ts",
        "tests/task248-active-tab-info-authorization-executor-bridge.test.ts",
        "tests/task247-active-tab-info-high-risk-authorization-misuse-guard.test.ts",
        "tests/task246-active-tab-info-high-risk-authorization-contract.test.ts",
        "tests/task245-active-tab-info-activation-executor-misuse-guard.test.ts",
        "tests/task244-active-tab-info-activation-executor-boundary.test.ts",
        "tests/task243-active-tab-info-activation-task-state-misuse-guard.test.ts",
        "tests/task242-active-tab-info-activation-task-state-machine.test.ts",
        "tests/task241-active-tab-info-activation-request-misuse-guard.test.ts",
        "tests/task240-active-tab-info-activation-request-contract.test.ts",
        "tests/task239-active-tab-info-release-surface-matrix.test.ts",
        "tests/task238-release-active-tab-info-prerequisite-readiness-misuse-guard.test.ts",
        "tests/task237-release-active-tab-info-live-enable-prerequisites-manifest.test.ts",
        "tests/task236-active-tab-info-live-enable-prerequisite-projection-guard.test.ts",
        "tests/task235-active-tab-info-live-enable-prerequisites.test.ts",
        "tests/task233-release-active-tab-info-runtime-transition-misuse-guard.test.ts",
        "tests/task232-release-active-tab-info-runtime-transition-projection.test.ts",
        "tests/task231-yeonjang-browser-active-tab-info-live-enable-state-machine.test.ts",
        "tests/task189-release-approval-workflow.test.ts",
        "tests/task012-release-package.test.ts",
        "tests/task230-release-active-tab-info-review-projection-misuse-guard.test.ts",
        "tests/task229-release-active-tab-info-live-enable-review-projection.test.ts",
        "tests/task228-yeonjang-browser-active-tab-info-live-enable-review.test.ts",
        "tests/task227-yeonjang-browser-active-tab-info-production-exposure-audit.test.ts",
        "tests/task226-release-approval-evidence-validator.test.ts",
        "tests/task225-release-active-tab-info-audit-artifact-verifier.test.ts",
        "tests/task224-release-active-tab-info-audit-projection-boundary.test.ts",
        "tests/task223-active-tab-info-release-gate-test-runner-summary-adapter.test.ts",
        "tests/task222-active-tab-info-release-gate-test-status-evidence-format.test.ts",
        "tests/task221-release-manifest-active-tab-info-evidence-input.test.ts",
        "tests/task220-yeonjang-browser-active-tab-info-release-gate-repository-evidence-adapter.test.ts",
        "tests/task219-yeonjang-browser-active-tab-info-release-gate-evidence-collector.test.ts",
        "tests/task217-yeonjang-browser-active-tab-info-release-gate-summary.test.ts",
        "tests/task216-yeonjang-browser-active-tab-info-review-ready-bundle.test.ts",
        "tests/task215-yeonjang-browser-active-tab-info-postcheck-llm-review-admission.test.ts",
        "tests/task214-yeonjang-browser-active-tab-info-runtime-result-assembler.test.ts",
      ],
      required: true,
      smoke: false,
    })
    expect(step?.description).not.toMatch(/enable.*live|default live smoke enabled|skill mapping enabled/iu)
    expect(step?.description).toContain("repository source/test evidence")
    expect(step?.description).toContain("evidence chain cleanup deletion dry-run review acknowledgement receipt misuse guard")
    expect(step?.description).toContain("evidence chain cleanup deletion dry-run review acknowledgement receipt")
    expect(step?.description).toContain("evidence chain cleanup deletion dry-run receipt surface matrix")
    expect(step?.description).toContain("evidence chain cleanup deletion dry-run receipt misuse guard")
    expect(step?.description).toContain("evidence chain cleanup deletion dry-run receipt")
    expect(step?.description).toContain("disabled live paths")
  })

  it("adds active tab info release gate to clean install checklist as required", () => {
    const checklist = buildCleanMachineInstallChecklist()

    expect(checklist).toEqual(expect.arrayContaining([
      {
        id: "release-approval-candidate-preparation",
        required: true,
        description:
          "Run release-package --dry-run --json, attach its sanitized releaseApprovalEvidence to performance and rollout approval candidates with release:prepare-approval-candidate, then approve with release:authorize. Operator output must contain only artifact id, checksum, packagePath, evidence count summary, readiness blocker state, and no threshold/baseline raw detail, raw audit JSON, URL, or local absolute path.",
      },
      {
        id: "yeonjang-browser-active-tab-info-release-gate",
        required: true,
        description:
          "Yeonjang browser.active_tab_info repository evidence, normalized test status evidence, stale/missing/skipped rejection, audit-only redaction, safe evidenceRef, runtime assembler, LLM review admission, and disabled live path regressions pass before any live handler or Skill mapping is enabled. Manual review and runtime transition summaries are release notes only and do not prove live enablement or user goal success.",
      },
    ]))
  })

  it("adds active tab info release gate status and disabled live paths to release notes", () => {
    const manifest = buildReleaseManifest({
      rootDir: process.cwd(),
      now: new Date("2026-07-22T00:00:00.000Z"),
      yeonjangBrowserActiveTabInfoReleaseGateEvidence: {
        moduleEvidence: ACTIVE_TAB_INFO_RELEASE_GATE_EVIDENCE_REQUIREMENTS.map((requirement) => ({
          gateId: requirement.gateId,
          present: true,
        })),
        testEvidence: ACTIVE_TAB_INFO_RELEASE_GATE_EVIDENCE_REQUIREMENTS.map((requirement) => ({
          testPath: requirement.testPath,
          status: "passed",
        })),
      },
    })

    expect(manifest.yeonjangBrowserActiveTabInfoReleaseGate).toMatchObject({
      schemaVersion: "yeonjang-browser-active-tab-info-release-gate-summary-v1",
      method: "browser.active_tab_info",
      gateStatus: "ready_for_manual_live_integration_review",
      liveIntegrationState: {
        rustLiveHandlerEnabled: false,
        skillMappingEnabled: false,
        productionBindingEnabled: false,
        defaultLiveSmokeEnabled: false,
      },
      addRustDispatchNow: false,
      addProductionBindingNow: false,
      enableSkillMappingNow: false,
      enableDefaultLiveSmokeNow: false,
    })
    expect(manifest.releaseNotes.knownLimitations).toContain(
      "Yeonjang browser.active_tab_info release gate: ready_for_manual_live_integration_review",
    )
    expect(manifest.releaseNotes.knownLimitations).toContain(
      "Yeonjang browser.active_tab_info live integration requires manual review; Rust live handler=false, Skill mapping=false, production binding=false, default live smoke=false.",
    )
  })
})
