import type { YeonjangBrowserActiveTabInfoFinalRetainedAcknowledgementCompletionCloseoutLedger } from "./yeonjang-browser-active-tab-info-final-retained-acknowledgement-completion-closeout-ledger.js";
export type YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceiptStatus = "ready";
export type YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceiptBlockingReasonCode = "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_receipt_ledger_not_ready" | "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_receipt_ref_invalid" | "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_receipt_product_log_evidence_ref_invalid" | "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_receipt_ack_ref_invalid";
export interface YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceiptInput {
    finalRetainedAcknowledgementCompletionCloseoutLedger: YeonjangBrowserActiveTabInfoFinalRetainedAcknowledgementCompletionCloseoutLedger;
    sanitizedOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceiptRef: string;
    productLogEvidenceRef: string;
    operatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementRef: string;
}
export type YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceipt = Readonly<{
    schemaVersion: "knowbee.yeonjang-browser-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-receipt.v1";
    method: "browser.active_tab_info";
    status: "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_receipt_ready" | "blocked";
    reasonCode: "active_tab_info_operator_final_retained_acknowledgement_completion_closeout_acknowledgement_receipt_ready" | "active_tab_info_operator_final_retained_acknowledgement_completion_closeout_acknowledgement_receipt_blocked";
    blockingReasonCodes?: readonly YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceiptBlockingReasonCode[];
    receipt?: Readonly<{
        operatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceiptId: string;
        finalRetainedAcknowledgementCompletionCloseoutLedgerId: string;
        sanitizedOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceiptRef: string;
        productLogEvidenceRef: string;
        operatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementRef: string;
        receiptStatus: YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceiptStatus;
    }>;
    releaseReadinessNow: false;
    publicationReadinessNow: false;
    enableSkillMappingNow: false;
    addProductionBindingNow: false;
    enableDefaultLiveSmokeNow: false;
}>;
export declare function buildYeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceipt(input: YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceiptInput): YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementReceipt;
//# sourceMappingURL=yeonjang-browser-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-receipt.d.ts.map