import type { YeonjangBrowserActiveTabInfoFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedger } from "./yeonjang-browser-active-tab-info-final-retained-acknowledgement-completion-closeout-acknowledgement-ledger.js";
export type YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceiptStatus = "ready";
export type YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceiptBlockingReasonCode = "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_ledger_receipt_ledger_not_ready" | "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_ledger_receipt_ref_invalid" | "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_ledger_receipt_product_log_evidence_ref_invalid" | "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_ledger_receipt_ack_ref_invalid";
export interface YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceiptInput {
    finalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedger: YeonjangBrowserActiveTabInfoFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedger;
    sanitizedOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceiptRef: string;
    productLogEvidenceRef: string;
    operatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerRef: string;
}
export type YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceipt = Readonly<{
    schemaVersion: "knowbee.yeonjang-browser-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-ledger-receipt.v1";
    method: "browser.active_tab_info";
    status: "operator_final_retained_acknowledgement_completion_closeout_acknowledgement_ledger_receipt_ready" | "blocked";
    reasonCode: "active_tab_info_operator_final_retained_acknowledgement_completion_closeout_acknowledgement_ledger_receipt_ready" | "active_tab_info_operator_final_retained_acknowledgement_completion_closeout_acknowledgement_ledger_receipt_blocked";
    blockingReasonCodes?: readonly YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceiptBlockingReasonCode[];
    receipt?: Readonly<{
        operatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceiptId: string;
        finalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerId: string;
        sanitizedOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceiptRef: string;
        productLogEvidenceRef: string;
        operatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerRef: string;
        receiptStatus: YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceiptStatus;
    }>;
    releaseReadinessNow: false;
    publicationReadinessNow: false;
    enableSkillMappingNow: false;
    addProductionBindingNow: false;
    enableDefaultLiveSmokeNow: false;
}>;
export declare function buildYeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceipt(input: YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceiptInput): YeonjangBrowserActiveTabInfoOperatorFinalRetainedAcknowledgementCompletionCloseoutAcknowledgementLedgerReceipt;
//# sourceMappingURL=yeonjang-browser-active-tab-info-operator-final-retained-acknowledgement-completion-closeout-acknowledgement-ledger-receipt.d.ts.map