export const KNOWBEE_PRODUCT_NAME = "Knowbee"
export const KNOWBEE_PRODUCT_NAME_KO = "노비"
export const DEFAULT_MAIN_AGENT_NAME_EN = KNOWBEE_PRODUCT_NAME
export const DEFAULT_MAIN_AGENT_NAME_KO = KNOWBEE_PRODUCT_NAME_KO
