const REMOTE_YEONJANG_TARGET = {
    targetKind: "yeonjang_remote",
    requiresTargetResolution: true,
    evidenceSourceKind: "yeonjang",
};
export const YEONJANG_TOOL_MAPPINGS = [
    {
        toolName: "yeonjang_status",
        methodIds: [],
        group: "system",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
    },
    {
        toolName: "yeonjang_broadcast_run",
        methodIds: [],
        group: "system",
        riskLevel: "dangerous",
        requiresApproval: true,
        ...REMOTE_YEONJANG_TARGET,
    },
    {
        toolName: "yeonjang_camera_list",
        methodIds: ["camera.list"],
        group: "camera",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_camera_access",
    },
    {
        toolName: "yeonjang_camera_capture",
        methodIds: ["camera.capture"],
        group: "camera",
        riskLevel: "moderate",
        requiresApproval: true,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_camera_access",
    },
    {
        toolName: "yeonjang_camera_permission_status",
        methodIds: ["camera.permission_status"],
        group: "camera",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_camera_access",
    },
    {
        toolName: "yeonjang_file_metadata",
        methodIds: ["file.metadata"],
        group: "files",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_file_read",
    },
    {
        toolName: "yeonjang_file_list",
        methodIds: ["file.list"],
        group: "files",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_file_read",
    },
    {
        toolName: "yeonjang_file_read",
        methodIds: ["file.read"],
        group: "files",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_file_read",
    },
    {
        toolName: "yeonjang_file_search",
        methodIds: ["file.search"],
        group: "files",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_file_read",
    },
    {
        toolName: "yeonjang_file_write",
        methodIds: ["file.write"],
        group: "files",
        riskLevel: "moderate",
        requiresApproval: true,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_file_write",
    },
    {
        toolName: "yeonjang_file_patch",
        methodIds: ["file.patch"],
        group: "files",
        riskLevel: "moderate",
        requiresApproval: true,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_file_write",
    },
    {
        toolName: "yeonjang_file_delete",
        methodIds: ["file.delete"],
        group: "files",
        riskLevel: "dangerous",
        requiresApproval: true,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_file_delete",
    },
    {
        toolName: "yeonjang_disk_info",
        methodIds: ["disk.info"],
        group: "disk",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_disk_read",
    },
    {
        toolName: "yeonjang_disk_usage",
        methodIds: ["disk.usage"],
        group: "disk",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_disk_read",
    },
    {
        toolName: "yeonjang_disk_exists",
        methodIds: ["disk.exists"],
        group: "disk",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_disk_read",
    },
    {
        toolName: "yeonjang_process_list",
        methodIds: ["process.list"],
        group: "process",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_process_read",
    },
    {
        toolName: "yeonjang_process_info",
        methodIds: ["process.info"],
        group: "process",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_process_read",
    },
    {
        toolName: "yeonjang_browser_list",
        methodIds: ["browser.list"],
        group: "browser",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_browser_read",
    },
    {
        toolName: "yeonjang_browser_active_hint",
        methodIds: ["browser.active_hint"],
        group: "browser",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_browser_read",
    },
    {
        toolName: "yeonjang_browser_open_url",
        methodIds: ["browser.open_url"],
        group: "browser",
        riskLevel: "moderate",
        requiresApproval: true,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_browser_control",
    },
    {
        toolName: "yeonjang_browser_focus",
        methodIds: ["browser.focus"],
        group: "browser",
        riskLevel: "moderate",
        requiresApproval: true,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_browser_control",
    },
    {
        toolName: "yeonjang_clipboard_read",
        methodIds: ["clipboard.read"],
        group: "clipboard",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_clipboard_read",
    },
    {
        toolName: "yeonjang_clipboard_write",
        methodIds: ["clipboard.write"],
        group: "clipboard",
        riskLevel: "moderate",
        requiresApproval: true,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_clipboard_write",
    },
    {
        toolName: "yeonjang_network_status",
        methodIds: ["network.status"],
        group: "network",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_network_read",
    },
    {
        toolName: "yeonjang_device_status",
        methodIds: ["device.status"],
        group: "device",
        riskLevel: "safe",
        requiresApproval: false,
        ...REMOTE_YEONJANG_TARGET,
        permissionSetting: "allow_device_status",
    },
];
export const YEONJANG_TOOL_NAMES = YEONJANG_TOOL_MAPPINGS.map((mapping) => mapping.toolName);
//# sourceMappingURL=tool-mapping.js.map